news_sentiment/board/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostCreateView,
    PostDetailView,
    PostDeleteView,
    PostEditView,
    CommentCreateView,
    CommentDeleteView,
    CommentEditView,
)

app_name = 'board'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/edit/', PostEditView.as_view(), name='post_edit'),
    path('post/<int:pk>/comment/create/', CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('comment/<int:pk>/edit/', CommentEditView.as_view(), name='comment_edit'),
]

news_sentiment/news_sentiment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analysis.urls')), # main page url
    path('accounts/', include('allauth.urls')),
    path('board/', include('board.urls')),
]

news_sentiment/board/models.py
from django.db import models
from django.conf import settings

User = settings.AUTH_USER_MODEL

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    view_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content
    
 

news_sentiment/board/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

news_sentiment/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import JsonResponse
from django.db.models import Count

class PostListView(View):
    
    def get(self, request):
        posts = Post.objects.annotate(comment_count=Count('comment')).order_by('-created_at')
        paginator = Paginator(posts, 10)  # Show 10 posts per page
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'page_obj': page_obj,
            'posts': posts,

        }
        
        return render(request, 'board/post_list.html', context)


class PostCreateView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = PostForm()
        return render(request, 'board/post_create.html', {'form': form})

    @method_decorator(login_required)
    def post(self, request):
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('board:post_detail', pk=post.pk)
        return render(request, 'board/post_create.html', {'form': form})


class PostDetailView(View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        comments = Comment.objects.filter(post=post)

        # 조회수 증가
        post.view_count += 1
        post.save()

        context = {
            'post': post,
            'comments': comments,
            'user': request.user,
        }
        return render(request, 'board/post_detail.html', context)


class PostDeleteView(View):
    @method_decorator(login_required)
    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        post.delete()
        return redirect('board:post_list')

    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        return render(request, 'board/post_delete.html', {'post': post})


class PostEditView(View):
    @method_decorator(login_required)
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        form = PostForm(instance=post)
        context = {
            'form': form,
            'post': post,
        }
        return render(request, 'board/post_edit.html', context)

    @method_decorator(login_required)
    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('board:post_detail', pk=post.pk)
        return render(request, 'board/post_edit.html', {'form': form})


class CommentCreateView(View):
    @method_decorator(login_required)
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        form = CommentForm()
        return render(request, 'board/comment_create.html', {'form': form})

    @method_decorator(login_required)
    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('board:post_detail', pk=post.pk)
        return render(request, 'board/comment_create.html', {'form': form})


class CommentDeleteView(View):
    @method_decorator(login_required)
    def post(self, request, pk):
        comment = get_object_or_404(Comment, pk=pk)
        if request.user != comment.author:
            return JsonResponse({'error': '댓글을 삭제할 권한이 없습니다.'}, status=403)

        comment.delete()

        return JsonResponse({'success': '댓글이 성공적으로 삭제되었습니다.'})


class CommentEditView(View):
    @method_decorator(login_required)
    def get(self, request, pk):
        comment = get_object_or_404(Comment, pk=pk)
        form = CommentForm(instance=comment)
        return render(request, 'board/comment_edit.html', {'form': form})

    @method_decorator(login_required)
    def post(self, request, pk):
        comment = get_object_or_404(Comment, pk=pk)
        post_pk = comment.post.pk
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.save()
            return redirect('board:post_detail', pk=post_pk)
        return render(request, 'board/comment_edit.html', {'form': form})

news_sentiment/board/templates/board/comment_edit.html
<form method="post" action="{% url 'comment_edit' comment.id %}" class="edit-comment-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">댓글 수정</button>
</form>

news_sentiment/board/templates/board/post_create.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>Create a Post</h1>
        <form method="POST" action="{% url 'board:post_create' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" id="title" name="title" required>
            </div>
            <div class="form-group">
                <label for="content">Content</label>
                <textarea class="form-control" id="content" name="content" rows="5" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
{% endblock %}

news_sentiment/board/templates/board/post_delete.html
{% extends "base.html" %}


{% block content %}
    <div class="container">
        <h1 class="my-custom-class">Delete Post</h1>
        <p>아래의 게시물을 삭제하시겠습니까?</p>
        <p>{{ post.title }}</p>
        <p>{{ post.content }}</p>
        <p>{{ post.created_at }}</p>
        
        <form method="POST" action="{% url 'board:post_delete' post.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">삭제</button>
            <a href="{% url 'board:post_detail' post.id %}" class="btn btn-secondary">취소</a>
        </form>
    </div>
{% endblock %}

news_sentiment/board/templates/board/post_detail.html
{% extends "base.html" %}
{% block title %}SentiNews 게시판 상세{% endblock  %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h1>{{ post.title }}</h1>
                <p>{{ post.content }}</p>
                <p>작성자: {{ post.author.username }}</p>
                <p>작성일: {{ post.created_at }}</p>

                {% if user == post.author %}
                    <a href="{% url 'board:post_edit' post.id %}" class="btn btn-primary">수정</a>
                    <a href="{% url 'board:post_delete' post.id %}" class="btn btn-danger">삭제</a>
                {% endif %}
                
                <a href="{% url 'board:post_list' %}" class="btn btn-secondary">목록</a>
                
                
                
                {% for comment in post.comment_set.all %}

                <div class="media mb-4">
                    <div class="media-body">
                        <h5 class="mt-0">{{ comment.content }}</h5>
                        <h5 class="mt-0">작성자: {{ comment.author.username }}</h5>
                        <h5 class="mt-0">작성일: {{ comment.created_at }}</h5>
                        {% if user == comment.author %}
                             <a href="#" class="delete-comment-text" data-comment-id="{{ comment.id }}" onclick="return confirmDeleteComment(this)">삭제</a>
                        {% endif %}
                    </div>
                </div>
                
                {% endfor %}
                
                
                <div class="card my-4">
                    <h5 class="card-header">댓글 작성</h5>
                    <div class="card-body">
                        <form method="POST" action="{% url 'board:comment_create' post.id %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="comment_content">댓글 내용</label>
                                <textarea class="form-control" id="comment_content" name="content" rows="3"></textarea>
                            </div>
                            <br>
                            <button type="submit" class="btn btn-primary">작성</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script>
    function confirmDeleteComment(element) {
        var confirmed = confirm('정말로 삭제하시겠습니까?');

        if (confirmed) {
            // 삭제를 진행하는 코드
            var commentId = element.getAttribute('data-comment-id');
            console.log(commentId);
            // AJAX 요청 보내기
            $.ajax({
                type: 'POST',
                url: '/board/comment/' + commentId + '/delete/',
                dataType: 'json',
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',  // Django에서 제공하는 CSRF 토큰
                },
                success: function(data) {
                    // 성공적으로 삭제되면 메시지를 표시하고 페이지 리로드 또는 다른 동작 수행
                    alert(data.success);
                    location.reload();  // 페이지 리로드 예시
                },
                error: function(xhr, status, error) {
                    // 삭제 실패 시 에러 메시지 표시
                    alert(xhr.responseJSON.error);
                }
            });
        } else {
            // 사용자가 취소한 경우의 동작
            alert('삭제가 취소되었습니다.');
        }

        return false;  // 기본 동작인 링크 이동을 막음
    }
</script>

{% endblock %}

news_sentiment/board/templates/board/post_edit.html
{% extends "base.html" %}
{% block title %}SentiNews 게시판 수정{% endblock  %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h1>게시판 수정</h1>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">제목</label>
                        <input type="text" class="form-control" id="title" name="title" value="{{ post.title }}">
                    </div>
                    <div class="form-group">
                        <label for="content">내용</label>
                        <textarea class="form-control" id="content" name="content" rows="5">{{ post.content }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">수정</button>
                </form>
                <a href="{% url 'board:post_detail' post.id %}" class="btn btn-secondary">취소</a>
            </div>
        </div>
    </div>
{% endblock %}

news_sentiment/board/templates/board/post_list.html
{% extends "base.html" %}

{% block title %} SentiNews 게시판{% endblock  %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1>SentiNews  게시판</h1>
            
            <a href="{% url 'board:post_create' %}" class="btn btn-primary">글쓰기</a>
            <!-- Add your board content here -->
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>번호</th>
                        <th>제목</th>
                        <th>작성자</th>
                        <th>작성일</th>
                        <th>조회수</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in posts %}
                    <tr>
                        <td>{{ post.id }}</td>
                        <td><a href="{% url 'board:post_detail' post.id %}">{{ post.title }}  [{{post.comment_count}}]</a></td>
                        <td>{{ post.author.username }}</td>
                        <td>{{ post.created_at }}</td>
                        <td>{{ post.view_count }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <!-- Add pagination here -->
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">처음</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전</a>
                </li>
                {% endif %}
                <li class="page-item active">
                    <span class="page-link">
                        페이지 {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
                    </span>
                </li>
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">다음</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">마지막</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}