news_sentiment/analysis/urls.py
# create analysis urls.py

# Path: news_sentiment\analysis\urls.py

from django.urls import path
from . import views

app_name = 'analysis'
urlpatterns = [

    path('', views.home, name='home'),
    path('stocks/', views.stocks, name='stocks'),

]

news_sentiment/board/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostCreateView,
    PostDetailView,
    PostDeleteView,
    PostEditView,
    CommentCreateView,
    CommentDeleteView,
    CommentEditView,
)

app_name = 'board'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/edit/', PostEditView.as_view(), name='post_edit'),
    path('post/<int:pk>/comment/create/', CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('comment/<int:pk>/edit/', CommentEditView.as_view(), name='comment_edit'),
]

news_sentiment/news_sentiment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analysis.urls')), # main page url
    path('accounts/', include('allauth.urls')),
    path('board/', include('board.urls')),
]

news_sentiment/templates/base.html
<!-- base.html -->

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'bootstrap/bootstrap-icons/font/bootstrap-icons.css' %}">
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<link rel="stylesheet" href="{% static 'css/base.css' %}">

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <title>SentiNews</title>
</head>
<body>

  <!-- 네비게이션 바 -->
  <nav class="py-2 bg-light border-bottom">
    <div class="container d-flex flex-wrap">
      <ul class="nav me-auto">
        <li class="nav-item"><a href="{% url 'analysis:home' %}" class="nav-link link-dark px-2 active" aria-current="page">SentiNews</a></li>
        <li class="nav-item"><a href="{% url 'analysis:stocks' %}" class="nav-link link-dark px-2">종목별 감성분석</a></li>
        <li class="nav-item"><a href="{% url 'board:post_list' %}" class="nav-link link-dark px-2">커뮤니티</a></li>
        <li class="nav-item"><a href="" class="nav-link link-dark px-2">Q&A</a></li>
        <li class="nav-item"><a href="" class="nav-link link-dark px-2">About</a></li>
      </ul>
      <ul class="nav">
        {% if user.is_authenticated %}
        <li class="nav-item"><a href="{% url 'account_reset_password' %}" class="nav-link link-dark px-2">Mypage</a></li>
        <li class="nav-item"><a href="{% url 'account_logout' %}" class="nav-link link-dark px-2">Logout</a></li>
        {% else %}
        <li class="nav-item"><a href="{% url 'account_login' %}" class="nav-link link-dark px-2">Login</a></li>
        <li class="nav-item"><a href="{% url 'account_signup' %}" class="nav-link link-dark px-2">Sign up</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
<!-- 네비게이션 바 끝-->

<!-- content 여기에 -->
{%block content%}

{%endblock%}
<!-- content 끝-->


<!-- footer 여기에 -->
<footer class="footer fixed-bottom py-3 bg-light">
  <div class="container">
    <span class="text-muted">SentiNews</span>
  </div>
</footer>
<!-- footer 끝 -->
</body>
</html>

news_sentiment/templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}